### ISSUE TITLE
Error with Bigger Pages

### ISSUE THREAD

**Issue by jlmacedo** [ycherkes/OrcaSql#3]
This is the error:

Loading Primary Record Page (1:844429225416932)
Exception thrown: 'System.IndexOutOfRangeException' in OrcaSql.Core.dll
System.IndexOutOfRangeException: O índice estava fora dos limites da matriz.
   em OrcaSql.Core.Engine.Records.PrimaryRecord..ctor(Byte[] bytes, Page page) na C:\Users\jlmac\source\repos\OrcaSQL\src\OrcaSql.Core\Engine\Records\PrimaryRecord.cs:linha 32
   em OrcaSql.Core.Engine.Pages.PrimaryRecordPage.parseRecords() na C:\Users\jlmac\source\repos\OrcaSQL\src\OrcaSql.Core\Engine\Pages\PrimaryRecordPage.cs:linha 30

**Comment by ycherkes** [comment]
SQL server has integer PageId - [proof](https://docs.microsoft.com/en-us/sql/relational-databases/system-dynamic-management-views/sys-dm-db-page-info-transact-sql?view=sql-server-ver16#:~:text=page_id%C2%A0,int)
So the PageId from your example is too big. 
I think the root of the problem is something else.

**Comment by ycherkes** [comment]
That's interesting, if pageId is Int64 - that means that PagePointer must use 10 bytes instead of 6 (4 bytes for PageId and 2 bytes for FileId)

Do you have access to SQL Server with this Db?

It's interesting to look at result of the next query:

```
SELECT DB_NAME(PA.database_id) [DataBase], 
    OBJECT_NAME(PA.object_id) [Table], SI.Name [Index], 
    is_allocated, allocated_page_file_id [file_id], 
    allocated_page_page_id [page_id], page_type_desc, 
    page_level, previous_page_page_id [previous_page_id], 
    next_page_page_id [next_page_id]
FROM sys.dm_db_database_page_allocations 
    (DB_ID('DADOSEIS'), 
         OBJECT_ID('AGING2'), 1, NULL, 'DETAILED') PA
         LEFT OUTER JOIN sys.indexes SI 
        ON SI.object_id = PA.object_id 
                   AND SI.index_id = PA.index_id
WHERE is_allocated = 1  
    and page_type in (1,2) -- INDEX_PAGE and DATA_PAGE Only
ORDER BY page_level DESC, is_allocated DESC,
         previous_page_page_id
```

**Comment by jlmacedo** [comment]
I trying to recover this table, maybe the problem is in the date colunm:

![Screenshot 2022-06-30 114803](https://user-images.githubusercontent.com/5131329/176708304-fb9fde50-089f-4553-8a1c-18880d15851d.png)

![image](https://user-images.githubusercontent.com/5131329/176708467-54472168-8ed9-417c-b854-24e35d897f2d.png)

**Comment by ycherkes** [comment]
Thank you. I'm still thinking that the so big PageId is the result of data corruption.

**Comment by jlmacedo** [comment]
I was comparing one database, look at the date colunm: 

![image](https://user-images.githubusercontent.com/5131329/176884376-698fb3db-7346-4922-895a-8ea32bbf951b.png)

**Comment by jlmacedo** [comment]
I fixed the problem, was the header of MDF file. Thank you!
