### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by AlexLevich** [ycherkes/OrcaSql#5]
System.ArgumentOutOfRangeException:The specified argument is out of range.

Parameter name:File with ID 4 is not part of this database.

in OrcaSql.Core.Engine.BufferManager.GetPageBytes(Int16 fileID, Int64 pageID, Boolean putResultToCache) BufferManager.cs:string 36
in OrcaSql.Core.Engine.Database.GetPageBytes(PagePointer pagePointer, Boolean putResultsToCache) Database.cs:string 138
in OrcaSql.Core.Engine.Database.GetPfsPage(PagePointer loc) Database.cs:string 236
in OrcaSql.Core.Engine.DataScanner.<ScanHeap>d__8.MoveNext() DataScanner.cs:string 164
in OrcaSql.Core.Engine.DataScanner.<ScanPartition>d__7.MoveNext() DataScanner.cs:string 149
in System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
in System.Linq.Enumerable.<TakeIterator>d__25`1.MoveNext()
in OrcaSql.OSMS.Main.ShowRows(IEnumerable`1 rows, Row schemaRow, String tableName, Int64 rowCount) Main.cs:string 514
in OrcaSql.OSMS.Main.LoadTable(String table, Nullable`1 schemaId, Int64 rowCount) Main.cs:string 450

sql server 2014 i open mdf file

here it crashes for me:
rows = scanner.ScanTable(table, schemaId, false).Take(takeRowCount)

I also have a LogCur.ndf file for this project

**Comment by ycherkes** [comment]
Hi, have you tried choosing multiple files (mdf+ndf) in the open dialog?

**Comment by AlexLevich** [comment]
I'm sorry I didn't notice for that, tomorrow I will definitely look and writing

**Comment by ycherkes** [comment]
> 



> I'm sorry I didn't notice for that, tomorrow I will definitely look and writing

Yeah, this tool is not so smart as SQL Server. So you must provide all the files explicitly.
